sonar.projectKey=Quetzacoalt91_autoupgrade
sonar.organization=quetzacoalt91

# Path to sources
sonar.sources=.
sonar.exclusions=**/tests/**,**/storybook/**

# Path to tests
# sonar.test.exclusions=./
# sonar.test.inclusions=tests/,_dev/tests/
sonar.tests=tests/,_dev/tests/

# Exclusions for copy-paste detection
sonar.cpd.exclusions=**/tests/**,**/storybook/stories/**
