<?php

/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License version 3.0
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    PrestaShop SA and Contributors <contact@prestashop.com>
 * @copyright Since 2007 PrestaShop SA and Contributors
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
 */

namespace PrestaShop\Module\AutoUpgrade\Migrations\Versions\Version_1_7_8_0;

use PrestaShop\Module\AutoUpgrade\Migrations\AbstractMigration;

class OrderSlipDropAndNewHooks extends AbstractMigration
{
    protected function up(): void
    {
        $this->addSql('DROP TABLE IF EXISTS `PREFIX_order_slip_detail_tax`');
        $this->addSql('INSERT INTO `PREFIX_hook` (`id_hook`, `name`, `title`, `description`, `position`) VALUES
  (NULL, \'actionPresentCart\', \'Cart Presenter\', \'This hook is called before a cart is presented\', \'1\'),
  (NULL, \'actionPresentOrder\', \'Order footer\', \'This hook is called before an order is presented\', \'1\'),
  (NULL, \'actionPresentOrderReturn\', \'Order Return Presenter\', \'This hook is called before an order return is presented\', \'1\'),
  (NULL, \'actionPresentProduct\', \'Product Presenter\', \'This hook is called before a product is presented\', \'1\'),
  (NULL, \'displayBanner\', \'Display Banner\', \'Use this hook for banners on top of every pages\', \'1\'),
  (NULL, \'actionModuleUninstallBefore\', \'Module uninstall before\', \'This hook is called before module uninstall process\', \'1\'),
  (NULL, \'actionModuleUninstallAfter\', \'Module uninstall after\', \'This hook is called at the end of module uninstall process\', \'1\'),
  (NULL, \'displayCartModalContent\', \'Cart Presenter\', \'This hook displays content in the middle of the window that appears after adding product to cart\', \'1\'),
  (NULL, \'displayCartModalFooter\', \'Cart Presenter\', \'This hook displays content in the bottom of window that appears after adding product to cart\', \'1\'),
  (NULL, \'displayHeaderCategory\', \'Category header\', \'This hook adds new blocks above the products listing in a category/search\', \'1\'),
  (NULL, \'actionCheckoutRender\', \'Checkout process render\', \'This hook is called when checkout process is constructed\', \'1\'),
  (NULL, \'actionPresentProductListing\', \'Product Listing Presenter\', \'This hook is called before a product listing is presented\', \'1\'),
  (NULL, \'actionGetProductPropertiesAfterUnitPrice\', \'Product Properties\', \'This hook is called after defining the properties of a product\', \'1\'),
  (NULL, \'actionProductSearchProviderRunQueryBefore\', \'Runs an action before ProductSearchProviderInterface::RunQuery()\', \'Required to modify an SQL query before executing it\', \'1\'),
  (NULL, \'actionProductSearchProviderRunQueryAfter\', \'Runs an action after ProductSearchProviderInterface::RunQuery()\', \'Required to return a previous state of an SQL query or/and to change a result of the SQL query after executing it\', \'1\'),
  (NULL, \'actionOverrideEmployeeImage\', \'Override Employee Image\', \'This hook is used to override the employee image\', \'1\'),
  (NULL, \'actionFrontControllerSetVariables\', \'Add variables in JavaScript object and Smarty templates\', \'Add variables to javascript object that is available in Front Office. These are also available in smarty templates in modules.your_module_name.\', \'1\'),
  (NULL, \'displayAdminGridTableBefore\', \'Display before Grid table\', \'This hook adds new blocks before Grid component table.\', \'1\'),
  (NULL, \'displayAdminGridTableAfter\', \'Display after Grid table\', \'This hook adds new blocks after Grid component table.\', \'1\'),
  (NULL, \'displayAdminOrderCreateExtraButtons\', \'Add buttons on the create order page dropdown\', \'Add buttons on the create order page dropdown\', \'1\'),
  (NULL, \'actionFeatureFlagForm\', \'Modify feature flag options form content\', \'This hook allows to modify the Feature Flag page form FormBuilder\', 1),
  (NULL, \'actionFeatureFlagSave\', \'Modify feature flag options form saved data\', \'This hook allows to modify the Feature Flag data being submitted through the form after it was saved\', 1),
  (NULL, \'actionProductFormBuilderModifier\', \'Modify product identifiable object form\', \'This hook allows to modify product identifiable object form content by modifying form builder data or FormBuilder itself\', \'1\'),
  (NULL, \'actionBeforeUpdateProductFormHandler\', \'Modify product identifiable object data before updating it\', \'This hook allows to modify product identifiable object form data before it was updated\', \'1\'),
  (NULL, \'actionAfterUpdateProductFormHandler\', \'Modify product identifiable object data after updating it\', \'This hook allows to modify product identifiable object form data after it was updated\', \'1\'),
  (NULL, \'actionBeforeCreateProductFormHandler\', \'Modify product identifiable object data before creating it\', \'This hook allows to modify product identifiable object form data before it was created\', \'1\'),
  (NULL, \'actionAfterCreateProductFormHandler\', \'Modify product identifiable object data after creating it\', \'This hook allows to modify product identifiable object form data after it was created\', \'1\'),
  (NULL,\'actionCustomerAddressGridDefinitionModifier\',\'Modify customer address grid definition\',\'This hook allows to alter customer address grid columns, actions and filters\',\'1\'),
  (NULL,\'actionCartRuleGridDefinitionModifier\',\'Modify cart rule grid definition\',\'This hook allows to alter cart rule grid columns, actions and filters\',\'1\'),
  (NULL,\'actionOrderStatesGridDefinitionModifier\',\'Modify order states grid definition\',\'This hook allows to alter order states grid columns, actions and filters\',\'1\'),
  (NULL,\'actionOrderReturnStatesGridDefinitionModifier\',\'Modify order return states grid definition\',\'This hook allows to alter order return states grid columns, actions and filters\',\'1\'),
  (NULL,\'actionOutstandingGridDefinitionModifier\',\'Modify outstanding grid definition\',\'This hook allows to alter outstanding grid columns, actions and filters\',\'1\'),
  (NULL,\'actionCarrierGridDefinitionModifier\',\'Modify carrier grid definition\',\'This hook allows to alter carrier grid columns, actions and filters\',\'1\'),
  (NULL,\'actionZoneGridDefinitionModifier\',\'Modify zone grid definition\',\'This hook allows to alter zone grid columns, actions and filters\',\'1\'),
  (NULL,\'actionCustomerDiscountGridQueryBuilderModifier\',\'Modify customer discount grid query builder\',\'This hook allows to alter Doctrine query builder for customer discount grid\',\'1\'),
  (NULL,\'actionCustomerAddressGridQueryBuilderModifier\',\'Modify customer address grid query builder\',\'This hook allows to alter Doctrine query builder for customer address grid\',\'1\'),
  (NULL,\'actionCartRuleGridQueryBuilderModifier\',\'Modify cart rule grid query builder\',\'This hook allows to alter Doctrine query builder for cart rule grid\',\'1\'),
  (NULL,\'actionOrderStatesGridQueryBuilderModifier\',\'Modify order states grid query builder\',\'This hook allows to alter Doctrine query builder for order states grid\',\'1\'),
  (NULL,\'actionOrderReturnStatesGridQueryBuilderModifier\',\'Modify order return states grid query builder\',\'This hook allows to alter Doctrine query builder for order return states grid\',\'1\'),
  (NULL,\'actionOutstandingGridQueryBuilderModifier\',\'Modify outstanding grid query builder\',\'This hook allows to alter Doctrine query builder for outstanding grid\',\'1\'),
  (NULL,\'actionCarrierGridQueryBuilderModifier\',\'Modify carrier grid query builder\',\'This hook allows to alter Doctrine query builder for carrier grid\',\'1\'),
  (NULL,\'actionZoneGridQueryBuilderModifier\',\'Modify zone grid query builder\',\'This hook allows to alter Doctrine query builder for zone grid\',\'1\'),
  (NULL,\'actionCustomerDiscountGridDataModifier\',\'Modify customer discount grid data\',\'This hook allows to modify customer discount grid data\',\'1\'),
  (NULL,\'actionCustomerAddressGridDataModifier\',\'Modify customer address grid data\',\'This hook allows to modify customer address grid data\',\'1\'),
  (NULL,\'actionCartRuleGridDataModifier\',\'Modify cart rule grid data\',\'This hook allows to modify cart rule grid data\',\'1\'),
  (NULL,\'actionOrderStatesGridDataModifier\',\'Modify order states grid data\',\'This hook allows to modify order states grid data\',\'1\'),
  (NULL,\'actionOrderReturnStatesGridDataModifier\',\'Modify order return states grid data\',\'This hook allows to modify order return states grid data\',\'1\'),
  (NULL,\'actionOutstandingGridDataModifier\',\'Modify outstanding grid data\',\'This hook allows to modify outstanding grid data\',\'1\'),
  (NULL,\'actionCarrierGridDataModifier\',\'Modify carrier grid data\',\'This hook allows to modify carrier grid data\',\'1\'),
  (NULL,\'actionZoneGridDataModifier\',\'Modify zone grid data\',\'This hook allows to modify zone grid data\',\'1\'),
  (NULL,\'actionCustomerDiscountGridFilterFormModifier\',\'Modify customer discount grid filters\',\'This hook allows to modify filters for customer discount grid\',\'1\'),
  (NULL,\'actionCustomerAddressGridFilterFormModifier\',\'Modify customer address grid filters\',\'This hook allows to modify filters for customer address grid\',\'1\'),
  (NULL,\'actionCartRuleGridFilterFormModifier\',\'Modify cart rule grid filters\',\'This hook allows to modify filters for cart rule grid\',\'1\'),
  (NULL,\'actionOrderStatesGridFilterFormModifier\',\'Modify order states grid filters\',\'This hook allows to modify filters for order states grid\',\'1\'),
  (NULL,\'actionOrderReturnStatesGridFilterFormModifier\',\'Modify order return states grid filters\',\'This hook allows to modify filters for order return states grid\',\'1\'),
  (NULL,\'actionOutstandingGridFilterFormModifier\',\'Modify outstanding grid filters\',\'This hook allows to modify filters for outstanding grid\',\'1\'),
  (NULL,\'actionCarrierGridFilterFormModifier\',\'Modify carrier grid filters\',\'This hook allows to modify filters for carrier grid\',\'1\'),
  (NULL,\'actionZoneGridFilterFormModifier\',\'Modify zone grid filters\',\'This hook allows to modify filters for zone grid\',\'1\'),
  (NULL,\'actionCustomerDiscountGridPresenterModifier\',\'Modify customer discount grid template data\',\'This hook allows to modify data which is about to be used in template for customer discount grid\',\'1\'),
  (NULL,\'actionCustomerAddressGridPresenterModifier\',\'Modify customer address grid template data\',\'This hook allows to modify data which is about to be used in template for customer address grid\',\'1\'),
  (NULL,\'actionCartRuleGridPresenterModifier\',\'Modify cart rule grid template data\',\'This hook allows to modify data which is about to be used in template for cart rule grid\',\'1\'),
  (NULL,\'actionOrderStatesGridPresenterModifier\',\'Modify order states grid template data\',\'This hook allows to modify data which is about to be used in template for order states grid\',\'1\'),
  (NULL,\'actionOrderReturnStatesGridPresenterModifier\',\'Modify order return states grid template data\',\'This hook allows to modify data which is about to be used in template for order return states grid\',\'1\'),
  (NULL,\'actionOutstandingGridPresenterModifier\',\'Modify outstanding grid template data\',\'This hook allows to modify data which is about to be used in template for outstanding grid\',\'1\'),
  (NULL,\'actionCarrierGridPresenterModifier\',\'Modify carrier grid template data\',\'This hook allows to modify data which is about to be used in template for carrier grid\',\'1\'),
  (NULL,\'actionZoneGridPresenterModifier\',\'Modify zone grid template data\',\'This hook allows to modify data which is about to be used in template for zone grid\',\'1\'),
  (NULL,\'actionCustomerDiscountGridDefinitionModifier\',\'Modify customer discount grid definition\',\'This hook allows to alter customer discount grid columns, actions and filters\',\'1\'),
  (NULL,\'actionPerformancePageSmartyForm\',\'Modify performance page smarty options form content\',\'This hook allows to modify performance page smarty options form FormBuilder\',\'1\'),
  (NULL,\'actionPerformancePageDebugModeForm\',\'Modify performance page debug mode options form content\',\'This hook allows to modify performance page debug mode options form FormBuilder\',\'1\'),
  (NULL,\'actionPerformancePageOptionalFeaturesForm\',\'Modify performance page optional features options form content\',\'This hook allows to modify performance page optional features options form FormBuilder\',\'1\'),
  (NULL,\'actionPerformancePageCombineCompressCacheForm\',\'Modify performance page combine compress cache options form content\',\'This hook allows to modify performance page combine compress cache options form FormBuilder\',\'1\'),
  (NULL,\'actionPerformancePageMediaServersForm\',\'Modify performance page media servers options form content\',\'This hook allows to modify performance page media servers options form FormBuilder\',\'1\'),
  (NULL,\'actionPerformancePagecachingForm\',\'Modify performance pagecaching options form content\',\'This hook allows to modify performance pagecaching options form FormBuilder\',\'1\'),
  (NULL,\'actionAdministrationPageGeneralForm\',\'Modify administration page general options form content\',\'This hook allows to modify administration page general options form FormBuilder\',\'1\'),
  (NULL,\'actionAdministrationPageUploadQuotaForm\',\'Modify administration page upload quota options form content\',\'This hook allows to modify administration page upload quota options form FormBuilder\',\'1\'),
  (NULL,\'actionAdministrationPageNotificationsForm\',\'Modify administration page notifications options form content\',\'This hook allows to modify administration page notifications options form FormBuilder\',\'1\'),
  (NULL,\'actionShippingPreferencesPageHandlingForm\',\'Modify shipping preferences page handling options form content\',\'This hook allows to modify shipping preferences page handling options form FormBuilder\',\'1\'),
  (NULL,\'actionShippingPreferencesPageCarrierOptionsForm\',\'Modify shipping preferences page carrier options options form content\',\'This hook allows to modify shipping preferences page carrier options options form FormBuilder\',\'1\'),
  (NULL,\'actionOrderPreferencesPageGeneralForm\',\'Modify order preferences page general options form content\',\'This hook allows to modify order preferences page general options form FormBuilder\',\'1\'),
  (NULL,\'actionOrderPreferencesPageGiftOptionsForm\',\'Modify order preferences page gift options options form content\',\'This hook allows to modify order preferences page gift options options form FormBuilder\',\'1\'),
  (NULL,\'actionProductPreferencesPageGeneralForm\',\'Modify product preferences page general options form content\',\'This hook allows to modify product preferences page general options form FormBuilder\',\'1\'),
  (NULL,\'actionProductPreferencesPagePaginationForm\',\'Modify product preferences page pagination options form content\',\'This hook allows to modify product preferences page pagination options form FormBuilder\',\'1\'),
  (NULL,\'actionProductPreferencesPagePageForm\',\'Modify product preferences page page options form content\',\'This hook allows to modify product preferences page page options form FormBuilder\',\'1\'),
  (NULL,\'actionProductPreferencesPageStockForm\',\'Modify product preferences page stock options form content\',\'This hook allows to modify product preferences page stock options form FormBuilder\',\'1\'),
  (NULL,\'actionGeolocationPageByAddressForm\',\'Modify geolocation page by address options form content\',\'This hook allows to modify geolocation page by address options form FormBuilder\',\'1\'),
  (NULL,\'actionGeolocationPageWhitelistForm\',\'Modify geolocation page whitelist options form content\',\'This hook allows to modify geolocation page whitelist options form FormBuilder\',\'1\'),
  (NULL,\'actionGeolocationPageOptionsForm\',\'Modify geolocation page options options form content\',\'This hook allows to modify geolocation page options options form FormBuilder\',\'1\'),
  (NULL,\'actionLocalizationPageConfigurationForm\',\'Modify localization page configuration options form content\',\'This hook allows to modify localization page configuration options form FormBuilder\',\'1\'),
  (NULL,\'actionLocalizationPageLocalUnitsForm\',\'Modify localization page local units options form content\',\'This hook allows to modify localization page local units options form FormBuilder\',\'1\'),
  (NULL,\'actionLocalizationPageAdvancedForm\',\'Modify localization page advanced options form content\',\'This hook allows to modify localization page advanced options form FormBuilder\',\'1\'),
  (NULL,\'actionFeatureFlagForm\',\'Modify feature flag options form content\',\'This hook allows to modify feature flag options form FormBuilder\',\'1\'),
  (NULL,\'actionPerformancePageSmartySave\',\'Modify performance page smarty options form saved data\',\'This hook allows to modify data of performance page smarty options form after it was saved\',\'1\'),
  (NULL,\'actionPerformancePageDebugModeSave\',\'Modify performance page debug mode options form saved data\',\'This hook allows to modify data of performance page debug mode options form after it was saved\',\'1\'),
  (NULL,\'actionPerformancePageOptionalFeaturesSave\',\'Modify performance page optional features options form saved data\',\'This hook allows to modify data of performance page optional features options form after it was saved\',\'1\'),
  (NULL,\'actionPerformancePageCombineCompressCacheSave\',\'Modify performance page combine compress cache options form saved data\',\'This hook allows to modify data of performance page combine compress cache options form after it was saved\',\'1\'),
  (NULL,\'actionPerformancePageMediaServersSave\',\'Modify performance page media servers options form saved data\',\'This hook allows to modify data of performance page media servers options form after it was saved\',\'1\'),
  (NULL,\'actionPerformancePagecachingSave\',\'Modify performance pagecaching options form saved data\',\'This hook allows to modify data of performance pagecaching options form after it was saved\',\'1\'),
  (NULL,\'actionAdministrationPageGeneralSave\',\'Modify administration page general options form saved data\',\'This hook allows to modify data of administration page general options form after it was saved\',\'1\'),
  (NULL,\'actionAdministrationPageUploadQuotaSave\',\'Modify administration page upload quota options form saved data\',\'This hook allows to modify data of administration page upload quota options form after it was saved\',\'1\'),
  (NULL,\'actionAdministrationPageNotificationsSave\',\'Modify administration page notifications options form saved data\',\'This hook allows to modify data of administration page notifications options form after it was saved\',\'1\'),
  (NULL,\'actionShippingPreferencesPageHandlingSave\',\'Modify shipping preferences page handling options form saved data\',\'This hook allows to modify data of shipping preferences page handling options form after it was saved\',\'1\'),
  (NULL,\'actionShippingPreferencesPageCarrierOptionsSave\',\'Modify shipping preferences page carrier options options form saved data\',\'This hook allows to modify data of shipping preferences page carrier options options form after it was saved\',\'1\'),
  (NULL,\'actionOrderPreferencesPageGeneralSave\',\'Modify order preferences page general options form saved data\',\'This hook allows to modify data of order preferences page general options form after it was saved\',\'1\'),
  (NULL,\'actionOrderPreferencesPageGiftOptionsSave\',\'Modify order preferences page gift options options form saved data\',\'This hook allows to modify data of order preferences page gift options options form after it was saved\',\'1\'),
  (NULL,\'actionProductPreferencesPageGeneralSave\',\'Modify product preferences page general options form saved data\',\'This hook allows to modify data of product preferences page general options form after it was saved\',\'1\'),
  (NULL,\'actionProductPreferencesPagePaginationSave\',\'Modify product preferences page pagination options form saved data\',\'This hook allows to modify data of product preferences page pagination options form after it was saved\',\'1\'),
  (NULL,\'actionProductPreferencesPagePageSave\',\'Modify product preferences page page options form saved data\',\'This hook allows to modify data of product preferences page page options form after it was saved\',\'1\'),
  (NULL,\'actionProductPreferencesPageStockSave\',\'Modify product preferences page stock options form saved data\',\'This hook allows to modify data of product preferences page stock options form after it was saved\',\'1\'),
  (NULL,\'actionGeolocationPageByAddressSave\',\'Modify geolocation page by address options form saved data\',\'This hook allows to modify data of geolocation page by address options form after it was saved\',\'1\'),
  (NULL,\'actionGeolocationPageWhitelistSave\',\'Modify geolocation page whitelist options form saved data\',\'This hook allows to modify data of geolocation page whitelist options form after it was saved\',\'1\'),
  (NULL,\'actionGeolocationPageOptionsSave\',\'Modify geolocation page options options form saved data\',\'This hook allows to modify data of geolocation page options options form after it was saved\',\'1\'),
  (NULL,\'actionLocalizationPageConfigurationSave\',\'Modify localization page configuration options form saved data\',\'This hook allows to modify data of localization page configuration options form after it was saved\',\'1\'),
  (NULL,\'actionLocalizationPageLocalUnitsSave\',\'Modify localization page local units options form saved data\',\'This hook allows to modify data of localization page local units options form after it was saved\',\'1\'),
  (NULL,\'actionLocalizationPageAdvancedSave\',\'Modify localization page advanced options form saved data\',\'This hook allows to modify data of localization page advanced options form after it was saved\',\'1\'),
  (NULL,\'actionFeatureFlagSave\',\'Modify feature flag options form saved data\',\'This hook allows to modify data of feature flag options form after it was saved\',\'1\'),
  (NULL,\'actionOrderStateFormBuilderModifier\',\'Modify order state identifiable object form\',\'This hook allows to modify order state identifiable object forms content by modifying form builder data or FormBuilder itself\',\'1\'),
  (NULL,\'actionOrderReturnStateFormBuilderModifier\',\'Modify order return state identifiable object form\',\'This hook allows to modify order return state identifiable object forms content by modifying form builder data or FormBuilder itself\',\'1\'),
  (NULL,\'actionZoneFormBuilderModifier\',\'Modify zone identifiable object form\',\'This hook allows to modify zone identifiable object forms content by modifying form builder data or FormBuilder itself\',\'1\'),
  (NULL,\'actionBeforeUpdateOrderStateFormHandler\',\'Modify order state identifiable object data before updating it\',\'This hook allows to modify order state identifiable object forms data before it was updated\',\'1\'),
  (NULL,\'actionBeforeUpdateOrderReturnStateFormHandler\',\'Modify order return state identifiable object data before updating it\',\'This hook allows to modify order return state identifiable object forms data before it was updated\',\'1\'),
  (NULL,\'actionBeforeUpdateZoneFormHandler\',\'Modify zone identifiable object data before updating it\',\'This hook allows to modify zone identifiable object forms data before it was updated\',\'1\'),
  (NULL,\'actionAfterUpdateOrderStateFormHandler\',\'Modify order state identifiable object data after updating it\',\'This hook allows to modify order state identifiable object forms data after it was updated\',\'1\'),
  (NULL,\'actionAfterUpdateOrderReturnStateFormHandler\',\'Modify order return state identifiable object data after updating it\',\'This hook allows to modify order return state identifiable object forms data after it was updated\',\'1\'),
  (NULL,\'actionAfterUpdateZoneFormHandler\',\'Modify zone identifiable object data after updating it\',\'This hook allows to modify zone identifiable object forms data after it was updated\',\'1\'),
  (NULL,\'actionBeforeCreateOrderStateFormHandler\',\'Modify order state identifiable object data before creating it\',\'This hook allows to modify order state identifiable object forms data before it was created\',\'1\'),
  (NULL,\'actionBeforeCreateOrderReturnStateFormHandler\',\'Modify order return state identifiable object data before creating it\',\'This hook allows to modify order return state identifiable object forms data before it was created\',\'1\'),
  (NULL,\'actionBeforeCreateZoneFormHandler\',\'Modify zone identifiable object data before creating it\',\'This hook allows to modify zone identifiable object forms data before it was created\',\'1\'),
  (NULL,\'actionAfterCreateOrderStateFormHandler\',\'Modify order state identifiable object data after creating it\',\'This hook allows to modify order state identifiable object forms data after it was created\',\'1\'),
  (NULL,\'actionAfterCreateOrderReturnStateFormHandler\',\'Modify order return state identifiable object data after creating it\',\'This hook allows to modify order return state identifiable object forms data after it was created\',\'1\'),
  (NULL,\'actionAfterCreateZoneFormHandler\',\'Modify zone identifiable object data after creating it\',\'This hook allows to modify zone identifiable object forms data after it was created\',\'1\'),
  (NULL,\'actionAdminAdministrationControllerPostProcessBefore\',\'On post-process in Admin Configure Advanced Parameters Administration Controller\',\'This hook is called on Admin Configure Advanced Parameters Administration post-process before processing any form\',\'1\'),
  (NULL,\'actionAdminAdministrationControllerPostProcessGeneralBefore\',\'On post-process in Admin Configure Advanced Parameters Administration Controller\',\'This hook is called on Admin Configure Advanced Parameters Administration post-process before processing the General form\',\'1\'),
  (NULL,\'actionAdminAdministrationControllerPostProcessNotificationsBefore\',\'On post-process in Admin Configure Advanced Parameters Administration Controller\',\'This hook is called on Admin Configure Advanced Parameters Administration post-process before processing the Notifications form\',\'1\'),
  (NULL,\'actionAdminAdministrationControllerPostProcessUploadQuotaBefore\',\'On post-process in Admin Configure Advanced Parameters Administration Controller\',\'This hook is called on Admin Configure Advanced Parameters Administration post-process before processing the Upload Quota form\',\'1\'),
  (NULL,\'actionAdminAdminShopParametersMetaControllerPostProcessBefore\',\'On post-process in Admin Configure Shop Parameters Meta Controller\',\'This hook is called on Admin Configure Shop Parameters Meta post-process before processing any form\',\'1\'),
  (NULL,\'actionAdminAdvancedParametersPerformanceControllerPostProcessBefore\',\'On post-process in Admin Configure Advanced Parameters Performance Controller\',\'This hook is called on Admin Configure Advanced Parameters Performance post-process before processing any form\',\'1\'),
  (NULL,\'actionAdminAdvancedParametersPerformanceControllerPostProcessCachingBefore\',\'On post-process in Admin Configure Advanced Parameters Performance Controller\',\'This hook is called on Admin Configure Advanced Parameters Performance post-process before processing the Caching form\',\'1\'),
  (NULL,\'actionAdminAdvancedParametersPerformanceControllerPostProcessCombineCompressCacheBefore\',\'On post-process in Admin Configure Advanced Parameters Performance Controller\',\'This hook is called on Admin Configure Advanced Parameters Performance post-process before processing the Combine Compress Cache form\',\'1\'),
  (NULL,\'actionAdminAdvancedParametersPerformanceControllerPostProcessDebugModeBefore\',\'On post-process in Admin Configure Advanced Parameters Performance Controller\',\'This hook is called on Admin Configure Advanced Parameters Performance post-process before processing the Debug Mode form\',\'1\'),
  (NULL,\'actionAdminAdvancedParametersPerformanceControllerPostProcessMediaServersBefore\',\'On post-process in Admin Configure Advanced Parameters Performance Controller\',\'This hook is called on Admin Configure Advanced Parameters Performance post-process before processing the Media Servers form\',\'1\'),
  (NULL,\'actionAdminAdvancedParametersPerformanceControllerPostProcessOptionalFeaturesBefore\',\'On post-process in Admin Configure Advanced Parameters Performance Controller\',\'This hook is called on Admin Configure Advanced Parameters Performance post-process before processing the Optional Features form\',\'1\'),
  (NULL,\'actionAdminAdvancedParametersPerformanceControllerPostProcessSmartyBefore\',\'On post-process in Admin Configure Advanced Parameters Performance Controller\',\'This hook is called on Admin Configure Advanced Parameters Performance post-process before processing the Smarty form\',\'1\'),
  (NULL,\'actionAdminInternationalGeolocationControllerPostProcessBefore\',\'On post-process in Admin Improve International Geolocation Controller\',\'This hook is called on Admin Improve International Geolocation post-process before processing any form\',\'1\'),
  (NULL,\'actionAdminInternationalGeolocationControllerPostProcessByIpAddressBefore\',\'On post-process in Admin Improve International Geolocation Controller\',\'This hook is called on Admin Improve International Geolocation post-process before processing the By Ip Address form\',\'1\'),
  (NULL,\'actionAdminInternationalGeolocationControllerPostProcessOptionsBefore\',\'On post-process in Admin Improve International Geolocation Controller\',\'This hook is called on Admin Improve International Geolocation post-process before processing the Options form\',\'1\'),
  (NULL,\'actionAdminInternationalGeolocationControllerPostProcessWhitelistBefore\',\'On post-process in Admin Improve International Geolocation Controller\',\'This hook is called on Admin Improve International Geolocation post-process before processing the Whitelist form\',\'1\'),
  (NULL,\'actionAdminInternationalLocalizationControllerPostProcessAdvancedBefore\',\'On post-process in Admin Improve International Localization Controller\',\'This hook is called on Admin Improve International Localization post-process before processing the Advanced form\',\'1\'),
  (NULL,\'actionAdminInternationalLocalizationControllerPostProcessBefore\',\'On post-process in Admin Improve International Localization Controller\',\'This hook is called on Admin Improve International Localization post-process before processing any form\',\'1\'),
  (NULL,\'actionAdminInternationalLocalizationControllerPostProcessConfigurationBefore\',\'On post-process in Admin Improve International Localization Controller\',\'This hook is called on Admin Improve International Localization post-process before processing the Configuration form\',\'1\'),
  (NULL,\'actionAdminInternationalLocalizationControllerPostProcessLocalUnitsBefore\',\'On post-process in Admin Improve International Localization Controller\',\'This hook is called on Admin Improve International Localization post-process before processing the Local Units form\',\'1\'),
  (NULL,\'actionAdminShippingPreferencesControllerPostProcessBefore\',\'On post-process in Admin Improve Shipping Preferences Controller\',\'This hook is called on Admin Improve Shipping Preferences post-process before processing any form\',\'1\'),
  (NULL,\'actionAdminShippingPreferencesControllerPostProcessCarrierOptionsBefore\',\'On post-process in Admin Improve Shipping Preferences Controller\',\'This hook is called on Admin Improve Shipping Preferences post-process before processing the Carrier Options form\',\'1\'),
  (NULL,\'actionAdminShippingPreferencesControllerPostProcessHandlingBefore\',\'On post-process in Admin Improve Shipping Preferences Controller\',\'This hook is called on Admin Improve Shipping Preferences post-process before processing the Handling form\',\'1\'),
  (NULL,\'actionAdminShopParametersMetaControllerPostProcessSeoOptionsBefore\',\'On post-process in Admin Configure Shop Parameters Meta Controller\',\'This hook is called on Admin Configure Shop Parameters Meta post-process before processing the Seo Options form\',\'1\'),
  (NULL,\'actionAdminShopParametersMetaControllerPostProcessSetUpUrlsBefore\',\'On post-process in Admin Configure Shop Parameters Meta Controller\',\'This hook is called on Admin Configure Shop Parameters Meta post-process before processing the SetUp Urls form\',\'1\'),
  (NULL,\'actionAdminShopParametersMetaControllerPostProcessShopUrlsBefore\',\'On post-process in Admin Configure Shop Parameters Meta Controller\',\'This hook is called on Admin Configure Shop Parameters Meta post-process before processing the Shop Urls form\',\'1\'),
  (NULL,\'actionAdminShopParametersMetaControllerPostProcessUrlSchemaBefore\',\'On post-process in Admin Configure Shop Parameters Meta Controller\',\'This hook is called on Admin Configure Shop Parameters Meta post-process before processing the Url Schema form\',\'1\'),
  (NULL,\'actionAdminShopParametersOrderPreferencesControllerPostProcessBefore\',\'On post-process in Admin Configure Shop Parameters Order Preferences Controller\',\'This hook is called on Admin Configure Shop Parameters Order Preferences post-process before processing any form\',\'1\'),
  (NULL,\'actionAdminShopParametersOrderPreferencesControllerPostProcessGeneralBefore\',\'On post-process in Admin Configure Shop Parameters Order Preferences Controller\',\'This hook is called on Admin Configure Shop Parameters Order Preferences post-process before processing the General form\',\'1\'),
  (NULL,\'actionAdminShopParametersOrderPreferencesControllerPostProcessGiftOptionsBefore\',\'On post-process in Admin Configure Shop Parameters Order Preferences Controller\',\'This hook is called on Admin Configure Shop Parameters Order Preferences post-process before processing the Gift Options form\',\'1\'),
  (NULL,\'displayAfterTitleTag\',\'After title tag\',\'Use this hook to add content after title tag\',\'1\')
ON DUPLICATE KEY UPDATE `title` = VALUES(`title`), `description` = VALUES(`description`)');
    }
}
